#!/usr/bin/env python3
import argparse
import shutil
import subprocess
import webbrowser
from pathlib import Path

ROOT_DIR = Path(__file__).parent
DOCS_DIR = ROOT_DIR / "docs"
BUILD_DIR = DOCS_DIR / "_build"
SOURCE_DIR = ROOT_DIR / "src/director"


def run_command(cmd, cwd=None):
    print(f"Running: {' '.join(cmd)}")
    subprocess.check_call(cmd, cwd=cwd)


def clean():
    print("Cleaning build artifacts...")
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
    
    # Remove autogenerated rst files (except the ones we manually manage)
    managed_files = ["index.rst", "examples.rst", "tutorial.rst", "api.rst"]
    for file in DOCS_DIR.glob("*.rst"):
        if file.name not in managed_files:
            file.unlink()
    print("Clean complete.")


def build():
    # print("Generating API docs...")
    # sphinx-apidoc [options] -o <outputdir> <sourcedir> [pathnames ...]
    # run_command(["sphinx-apidoc", "-o", str(DOCS_DIR), str(SOURCE_DIR), "--force"])

    print("Building HTML docs...")
    run_command(["sphinx-build", "-b", "html", str(DOCS_DIR), str(BUILD_DIR / "html")])
    print(f"Build complete. Docs are in {BUILD_DIR / 'html'}")


def view():
    index_path = BUILD_DIR / "html" / "index.html"
    if not index_path.exists():
        print("Docs not found. Please run 'build' first.")
        return

    print(f"Opening {index_path}...")
    webbrowser.open(f"file://{index_path.absolute()}")


def main():
    parser = argparse.ArgumentParser(description="Manage documentation")
    parser.add_argument("action", choices=["build", "clean", "view"], help="Action to perform")

    args = parser.parse_args()

    if args.action == "clean":
        clean()
    elif args.action == "build":
        build()
    elif args.action == "view":
        view()


if __name__ == "__main__":
    main()
