steps:

  - label: "🧹 Lint"
    key: "docker-lint"
    soft_fail: true
    command: |
      docker/run_docker_format_check.sh

  - label: "🧪 Test"
    key: "docker-test"
    depends_on: "docker-lint"
    command: |
      docker/run_docker_tests.sh

  - label: "📦 Docs"
    key: "docker-docs"
    depends_on: "docker-test"
    timeout_in_minutes: 10
    command: |
      docker/run_docker_docs.sh
    artifact_paths:
      - "docs.tar.gz"

  - label: "🚀 Trigger GitHub Deploy"
    key: "trigger-github-deploy"
    depends_on: "docker-docs"
    skip: false
    secrets:
      - GH_ACTIONS_TOKEN
    env:
      GITHUB_REPO_OWNER: patmarion
      GITHUB_REPO_NAME: director
      GITHUB_WORKFLOW_NAME: deploy_pages.yml
      GITHUB_REF: main
    command: |
      set -ex
      if [[ "$BUILDKITE_PIPELINE_SLUG" != "$${GITHUB_REPO_NAME}" ]]; then
        echo "Skipping GitHub deploy trigger for pipeline: $BUILDKITE_PIPELINE_SLUG"
        exit 0
      fi

      curl -L -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $${GH_ACTIONS_TOKEN}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/$${GITHUB_REPO_OWNER}/$${GITHUB_REPO_NAME}/actions/workflows/$${GITHUB_WORKFLOW_NAME}/dispatches \
        -d "{\"ref\":\"$${GITHUB_REF}\", \"inputs\":{\"build_number\":\"$BUILDKITE_BUILD_NUMBER\", \"artifact_filename\":\"docs.tar.gz\", \"bk_organization\":\"$BUILDKITE_ORGANIZATION_SLUG\", \"bk_pipeline\":\"$BUILDKITE_PIPELINE_SLUG\"}}"