env:
  UV_CACHE_DIR: "/root/.cache/uv"

steps:
  - label: "🔨 Build"
    key: "build"
    command: |
      set -ex
      uv sync --all-extras
    plugins:
      - docker#v5.11.0:
          image: "ghcr.io/astral-sh/uv:python3.10-bookworm-slim"
          volumes:
            - "/tmp/buildkite-uv-cache:/root/.cache/uv"
          workdir: "/workdir"

  - label: "🧹 Lint"
    key: "lint"
    depends_on: "build"
    soft_fail: true
    command: |
      set -ex
      uv sync --all-extras
      uv run ruff format --check .
      uv run ruff check .
    plugins:
      - docker#v5.11.0:
          image: "ghcr.io/astral-sh/uv:python3.10-bookworm-slim"
          volumes:
            - "/tmp/buildkite-uv-cache:/root/.cache/uv"
          workdir: "/workdir"

  - label: "🧪 Test"
    key: "test"
    depends_on: "lint"
    command: |
      set -ex
      apt-get update
      apt-get update && apt-get install -y \
        qt6-base-dev \
        libxcb-cursor0 \
        xvfb 
      uv sync --all-extras
      xvfb-run uv run pytest
    plugins:
      - docker#v5.11.0:
          image: "ghcr.io/astral-sh/uv:python3.10-bookworm-slim"
          volumes:
            - "/tmp/buildkite-uv-cache:/root/.cache/uv"
          workdir: "/workdir"

  - label: "📦 Deploy"
    key: "deploy"
    depends_on: "test"
    allow_dependency_failure: true
    plugins:
      - docker#v5.11.0:
          image: "ghcr.io/astral-sh/uv:python3.10-bookworm-slim"
          volumes:
            - "/tmp/buildkite-uv-cache:/root/.cache/uv"
          workdir: "/workdir"
    command: |
      set -ex
      uv sync --all-extras
      uv build --wheel
      docs/build.sh
      tar -czf docs.tar.gz -C docs/_build/html .
    artifact_paths:
      - "dist/*.whl"
      - "docs.tar.gz"

  - label: "🚀 Trigger GitHub Deploy"
    key: "trigger-github-deploy"
    depends_on: "deploy"
    secrets:
      - GH_ACTIONS_TOKEN
    env:
      GITHUB_REPO_OWNER: patmarion
      GITHUB_REPO_NAME: director
      GITHUB_WORKFLOW_NAME: deploy_pages.yml
      GITHUB_REF: main
    command: |
      set -ex
      curl -L -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $${GH_ACTIONS_TOKEN}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/$${GITHUB_REPO_OWNER}/$${GITHUB_REPO_NAME}/actions/workflows/$${GITHUB_WORKFLOW_NAME}/dispatches \
        -d "{\"ref\":\"$${GITHUB_REF}\", \"inputs\":{\"build_number\":\"$BUILDKITE_BUILD_NUMBER\", \"artifact_filename\":\"docs.tar.gz\", \"bk_organization\":\"$BUILDKITE_ORGANIZATION_SLUG\", \"bk_pipeline\":\"$BUILDKITE_PIPELINE_SLUG\"}}"